### ISSUE TITLE
[BUG] - Using annotations results in no ssl

### ISSUE THREAD

**Issue by Sceat** [vultr/vultr-cloud-controller-manager#226]
**Describe the bug**
For some reason using described annotations makes my endpoints serve http instead of https, I don't have enough knowledge to explain/understand properly but using those as per [the doc](https://docs.vultr.com/how-to-use-a-vultr-load-balancer-with-vke) results in `net::ERR_SSL_PROTOCOL_ERROR` and let's encrypt throwing `Server only speaks HTTP, not TLS`
```
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/vultr-loadbalancer-algorithm: "least_connections"
    service.beta.kubernetes.io/vultr-loadbalancer-healthcheck-protocol: 'http'
    service.beta.kubernetes.io/vultr-loadbalancer-healthcheck-path: '/health'
    service.beta.kubernetes.io/vultr-loadbalancer-healthcheck-check-interval: '10'
    service.beta.kubernetes.io/vultr-loadbalancer-healthcheck-response-timeout: '5'
    service.beta.kubernetes.io/vultr-loadbalancer-healthcheck-unhealthy-threshold: '5'
    service.beta.kubernetes.io/vultr-loadbalancer-healthcheck-healthy-threshold: '5'
```

**To Reproduce**
Use the [caddy ingress](https://github.com/caddyserver/ingress) helm-chart with the annotations above

**Expected behavior**
Not using the annotations make the endpoint work fine

**Comment by optik-aper** [comment]
@Sceat the annotation `service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"` will default the load balancer to only work on the HTTP so that might explain the behavior you're noticing.  I'm not familiar enough with caddy ingress to say for sure.  The Vultr help article you linked goes into detail on how to setup and use HTTPS with Vultr loadbalancers and all of the options required by the load balancer should be available through [annotations](https://github.com/vultr/vultr-cloud-controller-manager/blob/master/docs/load-balancers.md).
